/* istanbul ignore file */

export default {
  fallbackLng: 'en',
  namespace: 'translation',
  languages: [
    'ru',
    'en',
    'es',
    'ua',
    'zh_CN',
    'zh_TW',
    'da',
    'de',
    'fi',
    'ko',
    'it',
    'ja',
    'nl',
    'fr',
    'sv',
  ],
  langISOKeyToLangFullNameMap: {
    en: 'English',
    es: 'Español',
    ru: 'Русский',
    ua: 'Українська',
    da: 'Dansk',
    de: 'Deutsch',
    fi: 'Suomi',
    it: 'Italiano',
    nl: 'Nederlands',
    fr: 'Français',
    sv: 'Svenska',
    ko: '한국어',
    zh_CN: '简体中文',
    zh_TW: '繁體中文',
    ja: '日本語',
  },
};
